import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Apostolos',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Ornela',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
    products: [
      {
        //_id:'1',
        name: 'Greek gift No1',
        slug: 'various Greek gifts',
        category: 'Gifts',
        image: '/images/p1.jpg', 
        price: 60,
        countInStock: 10,
        brand: 'Greece',
        rating: 4.5,
        numReviews: 10,
        description: 'various Greek products',
      },
      {
        //_id:'2',
        name: 'Greek gift No2',
        slug: 'various Greek gifts2',
        category: 'Gifts',
        image: '/images/p2.jpg',
        price: 80,
        countInStock: 0,
        brand: 'Greece',
        rating: 4.0,
        numReviews: 10,
        description: 'various Greek products',
      },
      {
        //_id:'3',
        name: 'Greek gift No3',
        slug: 'various Greek gifts3',
        category: 'Gifts',
        image: '/images/p3.jpg',
        price: 70,
        countInStock: 15,
        brand: 'Greece',
        rating: 4.5,
        numReviews: 14,
        description: 'various Greek products',
      },
      {
        //_id:'4',
        name: 'Greek gift No4',
        slug: 'various Greek gifts4',
        category: 'Gifts',
        image: '/images/p4.jpg',
        price: 50,
        countInStock: 5,
        brand: 'Greece',
        rating: 4.5,
        numReviews: 10,
        description: 'various Greek products',
      },
    ],
  };
  export default data;